apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ci-staging-test
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0e090a234da1a2e11 }
      us-east-1b: { id: subnet-00edabddce351bcd8 }
      us-east-1c: { id: subnet-018813b00a37ccebc }
    public:
      us-east-1a: { id: subnet-03c070d19d6485f32 }
      us-east-1b: { id: subnet-022a8cb1c568159b4 }
      us-east-1c: { id: subnet-0a764513051e72ee5 }

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.medium
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
